server:
  port: 8001
spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
logging:
  level:
    com.xinshi.consumer: debug