server:
  port: 8001
spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  main:
    allow-circular-references: true
logging:
  level:
    com.xinshi.consumer: debug

feign:
  client:
    config:
      default:
        # 连接超时时间 5s
        connectTimeout: 5000
        # 读取超时时间 5s
        readTimeout: 5000

dubbo:
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: -1