server:
  port: 8001
spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
logging:
  level:
    com.xinshi.consumer: debug

feign:
  client:
    config:
      default:
        # 连接超时时间 5s
        connectTimeout: 5000
        # 读取超时时间 5s
        readTimeout: 5000


rocketmq:
  consumer:
    group: consumer_mq_group
    namesrv-addr: localhost:9876
    topic: FIRST_TEST_TOPIC
    tag: TagA