server:
  port: 8002
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - id: service-gateway-route
          uri: http://localhost:9001
          predicates:
#            - Method=GET
            - After=2025-03-07T09:33:37.8097189+08:00[Asia/Shanghai]
          filters:
            - AddRequestHeader=X-Request-red,blue
            - AddRequestParameter=color,red
            - AddResponseHeader=X-Response-Name,China
            - RemoveResponseHeader=x-response-city

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false