server:
  port: 8002
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - id: service-gateway-route
          uri: http://localhost:9001/provider/hello
          predicates:
            - Method=GET

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false